/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package waambokt

import kotlin.test.Test
import kotlin.test.assertNotNull

class MainTest {
    @Test fun `place holder test`() {
        assertNotNull(1, "Oh no, Int 1 is null! Do something!")
    }
}
